[tool.poetry]
name = "todo-app"
version = "0.1.0"
description = ""
authors = ["yusei <matsu.yusei3414@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
